### ISSUE TITLE
Mod Request - Bugfix for Facing the Right Direction

### ISSUE THREAD

**Issue by Zamiell** [Annosz/StardewValleyModding#2]
Hey Annosz,

If I am not mistaken, you messaged me once on Discord, but I can't seem to find your PM. I'm not sure how to contact you, so I'll just post an issue here and hope you see it.

I have a mod request and I am willing to donate for it.

### The Direction Facing Bugfix Mod

After performing the following actions the player will automatically be forced to face downwards:

- eating
- opening a treasure chest

This is a bug - the player should instead resume facing the direction that they were before they initiated the respective action.

In order to fix this, a mod could automatically buffer directional inputs and/or manually set the player's position's appropriately (whichever is easier to program).

This bug is particularly annoying when fishing. Consider the case where the player is fishing when facing to the right. After many casts, the player is almost out of energy, so they eat a fish. Now, after the eating animation is finished, the player has to manually press the right arrow key in order to reposition the character back to the way that they initially were, and *then* perform another cast.

With this hypothetical mod enabled, the player in this situation would simply be able to click to begin casting again without having to press anything in the keyboard.

**Comment by Annosz** [comment]
Hi Zamiell!

Thanks for the mod suggestion, I will look into how it can be achieved :) 

I think we still must be connected on Discord, so it's weird if you haven't found me. My username is the same as here - Annosz.

**Comment by Zamiell** [comment]
What is the 4 digit number suffix for your username? e.g. Annosz#1234

**Comment by Annosz** [comment]
The mod is available on the [Nexus ](https://www.nexusmods.com/stardewvalley/mods/6946):)

**Comment by Zamiell** [comment]
Thank you!
